spring:

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: springuser
    password: aaaaaa

  cache:
    type: hazelcast

logging:

  level:
    org:
      springframework:
        web: DEBUG